# Generated by Django 4.0.2 on 2023-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/recipe/ingredients/'),
        ),
    ]
