# Generated by Django 4.0.2 on 2023-05-09 17:53

from django.conf import settings
from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0004_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe_step',
            name='image',
            field=models.ImageField(blank=True, upload_to=recipe.models.upload_location_instructions),
        ),
    ]
