# Generated by Django 4.0.2 on 2023-05-18 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0005_recipe_likes_alter_recipe_step_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
